ENVIRONMENT:
  MAX_EPISODE_STEPS: 5000
SIMULATOR:
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  FORWARD_STEP_SIZE: 0.1
  ACTION_SPACE_CONFIG: "v1"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR', 'SEMANTIC_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.18
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: True 
  SEMANTIC_SENSOR:
    WIDTH: 320
    HEIGHT: 640
    HFOV: 90
    POSITION: [0, 0.88, 0]
    ORIENTATION: [-0.785, 0.0, 0.0]
  RGB_SENSOR:
    WIDTH: 320
    HEIGHT: 640
    HFOV: 90
    POSITION: [0, 0.88, 0]
    ORIENTATION: [-0.785, 0.0, 0.0]
  DEPTH_SENSOR:
    WIDTH: 320
    HEIGHT: 640
    HFOV: 90
    MIN_DEPTH: 0.0
    MAX_DEPTH: 5.0
    POSITION: [0, 0.88, 0]
    ORIENTATION: [-0.785, 0.0, 0.0]
TASK:
  TYPE: ObjectNav-v1
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "LOOK_UP", "LOOK_DOWN"]
  SENSORS: ['GPS_SENSOR', 'COMPASS_SENSOR']
  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']
  SUCCESS:
    SUCCESS_DISTANCE: 0.2

DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  DATA_PATH: "data/datasets/objectnav/gibson/v1/{split}/{split}.json.gz"
  EPISODES_DIR: "data/datasets/objectnav/gibson/v1/{split}/"
  SCENES_DIR: "data/scene_datasets/"